from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1184, 995)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("EasyChord.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.btnPlay = QtWidgets.QPushButton(self.frame_4)
        self.btnPlay.setGeometry(QtCore.QRect(0, 10, 120, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btnPlay.setFont(font)
        self.btnPlay.setStyleSheet("background-color: rgb(241, 241, 241);")
        self.btnPlay.setObjectName("btnPlay")
        self.btnGuardarSet = QtWidgets.QPushButton(self.frame_4)
        self.btnGuardarSet.setGeometry(QtCore.QRect(190, 10, 130, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btnGuardarSet.setFont(font)
        self.btnGuardarSet.setStyleSheet("background-color: rgb(241, 241, 241);")
        self.btnGuardarSet.setObjectName("btnGuardarSet")
        self.gridLayout_2.addWidget(self.frame_4, 4, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(350, 100))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.btnAbrirDirectorio = QtWidgets.QPushButton(self.frame_3)
        self.btnAbrirDirectorio.setGeometry(QtCore.QRect(180, 40, 150, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btnAbrirDirectorio.setFont(font)
        self.btnAbrirDirectorio.setStyleSheet("background-color: rgb(241, 241, 241);")
        self.btnAbrirDirectorio.setObjectName("btnAbrirDirectorio")
        self.lblListaCanciones = QtWidgets.QLabel(self.frame_3)
        self.lblListaCanciones.setGeometry(QtCore.QRect(0, 10, 180, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.lblListaCanciones.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblListaCanciones.setFont(font)
        self.lblListaCanciones.setStyleSheet("color: rgb(63, 63, 63)\n"
"")
        self.lblListaCanciones.setObjectName("lblListaCanciones")
        self.btnAbrirCancion = QtWidgets.QPushButton(self.frame_3)
        self.btnAbrirCancion.setGeometry(QtCore.QRect(0, 40, 150, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btnAbrirCancion.setFont(font)
        self.btnAbrirCancion.setStyleSheet("background-color: rgb(241, 241, 241);")
        self.btnAbrirCancion.setObjectName("btnAbrirCancion")
        self.gridLayout_2.addWidget(self.frame_3, 0, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMinimumSize(QtCore.QSize(350, 65))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.btnAgregarSet = QtWidgets.QPushButton(self.frame_5)
        self.btnAgregarSet.setGeometry(QtCore.QRect(0, 40, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btnAgregarSet.setFont(font)
        self.btnAgregarSet.setStyleSheet("background-color: rgb(241, 241, 241);")
        self.btnAgregarSet.setObjectName("btnAgregarSet")
        self.btnCargarSet = QtWidgets.QPushButton(self.frame_5)
        self.btnCargarSet.setGeometry(QtCore.QRect(220, 40, 100, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btnCargarSet.setFont(font)
        self.btnCargarSet.setStyleSheet("background-color: rgb(241, 241, 241);")
        self.btnCargarSet.setObjectName("btnCargarSet")
        self.btnQuitarSet = QtWidgets.QPushButton(self.frame_5)
        self.btnQuitarSet.setGeometry(QtCore.QRect(110, 40, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btnQuitarSet.setFont(font)
        self.btnQuitarSet.setStyleSheet("background-color: rgb(241, 241, 241);")
        self.btnQuitarSet.setObjectName("btnQuitarSet")
        self.lblSet = QtWidgets.QLabel(self.frame_5)
        self.lblSet.setGeometry(QtCore.QRect(0, 10, 170, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.lblSet.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblSet.setFont(font)
        self.lblSet.setStyleSheet("color: rgb(63, 63, 63)")
        self.lblSet.setObjectName("lblSet")
        self.gridLayout_2.addWidget(self.frame_5, 2, 0, 1, 1)
        self.listaCanciones = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listaCanciones.sizePolicy().hasHeightForWidth())
        self.listaCanciones.setSizePolicy(sizePolicy)
        self.listaCanciones.setMinimumSize(QtCore.QSize(350, 300))
        self.listaCanciones.setAlternatingRowColors(True)
        self.listaCanciones.setObjectName("listaCanciones")
        self.gridLayout_2.addWidget(self.listaCanciones, 1, 0, 1, 1)
        self.listaPlay = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listaPlay.sizePolicy().hasHeightForWidth())
        self.listaPlay.setSizePolicy(sizePolicy)
        self.listaPlay.setMinimumSize(QtCore.QSize(350, 300))
        self.listaPlay.setAcceptDrops(True)
        self.listaPlay.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.listaPlay.setAlternatingRowColors(True)
        self.listaPlay.setObjectName("listaPlay")
        self.gridLayout_2.addWidget(self.listaPlay, 3, 0, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 100))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btnBajar = QtWidgets.QPushButton(self.frame)
        self.btnBajar.setGeometry(QtCore.QRect(160, 40, 150, 28))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(241, 241, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(241, 241, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(241, 241, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(241, 241, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(241, 241, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(241, 241, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(241, 241, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(241, 241, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(241, 241, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.btnBajar.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btnBajar.setFont(font)
        self.btnBajar.setStyleSheet("background-color: rgb(241, 241, 241);")
        self.btnBajar.setObjectName("btnBajar")
        self.lblCancion = QtWidgets.QLabel(self.frame)
        self.lblCancion.setGeometry(QtCore.QRect(0, 10, 90, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.lblCancion.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblCancion.setFont(font)
        self.lblCancion.setStyleSheet("color: rgb(63, 63, 63)")
        self.lblCancion.setObjectName("lblCancion")
        self.btnSubir = QtWidgets.QPushButton(self.frame)
        self.btnSubir.setGeometry(QtCore.QRect(0, 40, 150, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btnSubir.setFont(font)
        self.btnSubir.setStyleSheet("background-color: rgb(241, 241, 241);")
        self.btnSubir.setObjectName("btnSubir")
        self.btnNuevaCancion = QtWidgets.QPushButton(self.frame)
        self.btnNuevaCancion.setGeometry(QtCore.QRect(370, 40, 150, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btnNuevaCancion.setFont(font)
        self.btnNuevaCancion.setStyleSheet("background-color: rgb(241, 241, 241);")
        self.btnNuevaCancion.setObjectName("btnNuevaCancion")
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.cancionTE = QtWidgets.QTextEdit(self.centralwidget)
        self.cancionTE.setMinimumSize(QtCore.QSize(600, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cancionTE.setFont(font)
        self.cancionTE.setPlaceholderText("")
        self.cancionTE.setObjectName("cancionTE")
        self.gridLayout.addWidget(self.cancionTE, 1, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.btnGuardarCancion = QtWidgets.QPushButton(self.frame_2)
        self.btnGuardarCancion.setGeometry(QtCore.QRect(320, 10, 160, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btnGuardarCancion.setFont(font)
        self.btnGuardarCancion.setStyleSheet("background-color: rgb(241, 241, 241);")
        self.btnGuardarCancion.setObjectName("btnGuardarCancion")
        self.btnExportarPDF = QtWidgets.QPushButton(self.frame_2)
        self.btnExportarPDF.setGeometry(QtCore.QRect(140, 10, 160, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btnExportarPDF.setFont(font)
        self.btnExportarPDF.setStyleSheet("background-color: rgb(241, 241, 241);")
        self.btnExportarPDF.setObjectName("btnExportarPDF")
        self.gridLayout.addWidget(self.frame_2, 2, 0, 1, 1)
        self.cancionTE2 = QtWidgets.QTextEdit(self.centralwidget)
        self.cancionTE2.setObjectName("cancionTE2")
        self.gridLayout.addWidget(self.cancionTE2, 1, 1, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1184, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EasyChord"))
        self.btnPlay.setText(_translate("MainWindow", "Play Canción"))
        self.btnGuardarSet.setText(_translate("MainWindow", "Guardar Set"))
        self.btnAbrirDirectorio.setText(_translate("MainWindow", "Abrir Directorio"))
        self.lblListaCanciones.setText(_translate("MainWindow", "Lista De Canciones:"))
        self.btnAbrirCancion.setText(_translate("MainWindow", "Abrir Canción"))
        self.btnAgregarSet.setText(_translate("MainWindow", "Agregar"))
        self.btnCargarSet.setText(_translate("MainWindow", "Cargar Set"))
        self.btnQuitarSet.setText(_translate("MainWindow", "Quitar"))
        self.lblSet.setText(_translate("MainWindow", "Set De Canciones:"))
        self.btnBajar.setText(_translate("MainWindow", "Transportar -"))
        self.lblCancion.setText(_translate("MainWindow", "Canción:"))
        self.btnSubir.setText(_translate("MainWindow", "Transportar +"))
        self.btnNuevaCancion.setText(_translate("MainWindow", "Nueva Canción"))
        self.btnGuardarCancion.setText(_translate("MainWindow", "Guardar Cambios"))
        self.btnExportarPDF.setText(_translate("MainWindow", "Exportar PDF"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

